name: ci
on:
  push:
    branches: ["main"]

env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/liatrio-exercise

jobs:
  build-verify-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Build the image and load it locally so we can run tests against it
      - name: Build (load for verification)
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: ${{ env.IMAGE }}:verify

      # 2) Run the container and expose app port 8080 on host port 80 (the verifier expects :80)
      - name: Start container on port 80
        run: |
          docker run -d --rm --name app -p 80:8080 ${{ env.IMAGE }}:verify
          for i in {1..30}; do curl -fsS http://localhost/ >/dev/null && break || sleep 1; done
          curl -fsS http://localhost/ >/dev/null

      # 3) Verify using a known-good commit of the Liatrio action
      - name: Apprentice verification
        uses: liatrio/github-actions/apprentice-action@0b41561cca6822cc8d880fe0e49e7807a41fdf91

      - name: Stop container
        if: always()
        run: docker rm -f app

      # 4) Log in and push uniquely tagged images to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (latest + unique)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:run-${{ github.run_number }}
