name: ci
on:
  push:
    branches: ["main"]

env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/liatrio-exercise

jobs:
  build-verify-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Build image and load it locally
      - name: Build (load for verification)
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: ${{ env.IMAGE }}:verify

      # 2) Start container and publish host:80 -> container:8080
      - name: Start container on port 80
        run: |
          echo "RAW:"
          curl -sv http://localhost/ 2>&1 | sed -n 's/^< //p'
          set -euo pipefail
          docker run -d --rm --name app -p 80:8080 ${{ env.IMAGE }}:verify
          # wait until the app responds on http://localhost/ (port 80)
          for i in {1..30}; do
            if curl -fsS http://localhost/ >/dev/null; then
              echo "App is up on port 80"
              break
            fi
            sleep 1
          done
          # assert it really is up (fails the step if not)
          curl -fsS http://localhost/ >/dev/null

      # 3) Verify (explicitly tell it to use port 80)
      - name: Apprentice verification
        uses: liatrio/github-actions/apprentice-action@master

      # Print helpful info only if the verification fails
      - name: Debug on failure
        if: failure()
        run: |
          echo "----- docker ps -----"
          docker ps -a || true
          echo "----- container logs -----"
          docker logs app || true
          echo "----- curl localhost (raw) -----"
          curl -v http://localhost/ || true

      - name: Stop container
        if: always()
        run: docker rm -f app

      # 4) Push to Docker Hub with unique tags
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (latest + unique)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:run-${{ github.run_number }}
            ${{ env.IMAGE }}:${{ github.sha }}
