name: ci
on:
  push:
    branches: ["main"]

env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/liatrio-exercise

jobs:
  build-verify-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Build image and load it locally
      - uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: ${{ env.IMAGE }}:verify

      # 2) Run container so the verifier can reach http://localhost:80
      - run: |
          docker run -d --rm --name app -p 80:8080 ${{ env.IMAGE }}:verify
          for i in {1..20}; do curl -fsS http://localhost/ && break || sleep 1; done

      # 3) Verify (this is the step from the screenshot)
      - uses: liatrio/github-actions/apprentice-action@master

      - if: always()
        run: docker rm -f app

      # 4) Log in and push uniquely tagged images
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:run-${{ github.run_number }}
            ${{ env.IMAGE }}:${{ github.sha }}
