name: ci
on:
  push:
    branches: ["main"]

env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/liatrio-exercise

jobs:
  build-verify-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Build image and load it locally
      - name: Build (load for verification)
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: ${{ env.IMAGE }}:verify

      # 2) Start container and publish container:8080 on host:80
      - name: Start container on port 80
        run: |
          docker run -d --rm --name app -p 80:8080 ${{ env.IMAGE }}:verify
          # wait until the app responds on http://localhost/ (port 80)
          for i in {1..30}; do curl -fsS http://localhost/ && break || sleep 1; done

      # 3) Run Liatrio's verifier (defaults to port 80)
      - name: Apprentice verification
        uses: liatrio/github-actions/apprentice-action@master

      - name: Stop container
        if: always()
        run: docker rm -f app

      # 4) Push to Docker Hub with unique tags
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (latest + unique)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:run-${{ github.run_number }}
            ${{ env.IMAGE }}:${{ github.sha }}
